In [ ]:
1. Create a null vector of size 10 but the fifth value which is 1.

In [1]:
import numpy as np


arr = np.zeros(10,dtype = int)
arr[4] = 1

print(arr)

[0 0 0 0 1 0 0 0 0 0]


In [ ]:
2. Create a vector with values ranging from 10 to 49.

In [2]:
array_1 = np.arange(10,50)

array_1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [ ]:
3. Create a 3x3 matrix with values ranging from 0 to 8

In [3]:
array_2 = np.arange(0,9).reshape(3,3)

print(array_2)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
4. Find indices of non-zero elements from [1,2,0,0,4,0]

In [4]:
n_array = np.array([1,2,0,0,4,0])

print("Original array:")
print(n_array)

# np.nonzero()
print("\nIndices of null elements:")

res = np.nonzero(n_array == 0)
print(res)

Original array:
[1 2 0 0 4 0]

Indices of null elements:
(array([2, 3, 5], dtype=int64),)


In [ ]:
5. Create a 10x10 array with random values and find the minimum and maximum values.

In [5]:
import numpy as np
n_array = np.random.random((10,10))

print("the original array",n_array)

print("\n\n")
print("the minimum value of n_array: \n",n_array.min())
      
print("\n\n")
print("the maximun value of n_array: \n",n_array.max())

the original array [[0.42275974 0.67559577 0.59322373 0.86848534 0.67506989 0.69210864
  0.62297474 0.01192937 0.35848414 0.51160261]
 [0.1989405  0.653398   0.63405696 0.7730158  0.03582163 0.98843865
  0.47152048 0.49576486 0.81206355 0.7990695 ]
 [0.35397406 0.79175243 0.613527   0.72603575 0.01029626 0.78526792
  0.23221622 0.02840662 0.76238976 0.11565497]
 [0.45529402 0.93789444 0.66288619 0.37463838 0.38798018 0.26277031
  0.3641357  0.95180548 0.28315986 0.89435678]
 [0.63568356 0.10066355 0.92642959 0.25552108 0.85788268 0.41690212
  0.15425377 0.22668826 0.82126518 0.27961993]
 [0.9481426  0.98019407 0.68570775 0.39012927 0.10332011 0.57049702
  0.75410938 0.09287457 0.23291426 0.2176356 ]
 [0.53061849 0.13334429 0.12760735 0.72379849 0.16394334 0.22429482
  0.59961888 0.7500895  0.63953592 0.57519243]
 [0.42041826 0.11823687 0.59260203 0.44578289 0.01368444 0.27161845
  0.12782052 0.84003693 0.16338457 0.01545124]
 [0.48551722 0.86708148 0.54821887 0.78909907 0.58553384 0.83

In [ ]:
6. Create a random vector of size 30 and find the mean value.

In [6]:
import numpy as np

z = np.random.random(30)
print("the random array is: \n",z)

mean_1 = z.mean()
print("\n\nthe mean value of array: \n ",mean_1)

the random array is: 
 [0.69773072 0.49257576 0.9889403  0.27813153 0.113439   0.45554602
 0.01763001 0.8423864  0.22810676 0.45077164 0.50132833 0.86413366
 0.34420875 0.27465991 0.05755868 0.24245486 0.03772599 0.29484247
 0.60831166 0.66740981 0.3907142  0.55132541 0.77190228 0.94028538
 0.2512461  0.26798097 0.21728258 0.16519711 0.72514962 0.30659641]


the mean value of array: 
  0.4348524114357956
